sudo pacman --noconfirm -S accountsservice
sudo pacman --noconfirm -S alacritty
sudo pacman --noconfirm -S alsa-firmware
sudo pacman --noconfirm -S alsa-plugins
sudo pacman --noconfirm -S alsa-utils
sudo pacman --noconfirm -S amd-ucode
sudo pacman --noconfirm -S aspell
sudo pacman --noconfirm -S astroterm
sudo pacman --noconfirm -S b43-fwcutter
sudo pacman --noconfirm -S base
sudo pacman --noconfirm -S base-devel
sudo pacman --noconfirm -S bash-completion
sudo pacman --noconfirm -S bc
sudo pacman --noconfirm -S bind
sudo pacman --noconfirm -S bluez
sudo pacman --noconfirm -S bluez-utils
sudo pacman --noconfirm -S btrfs-progs
sudo pacman --noconfirm -S cantarell-fonts
sudo pacman --noconfirm -S cava
sudo pacman --noconfirm -S chafa
sudo pacman --noconfirm -S clipman
sudo pacman --noconfirm -S cloc
sudo pacman --noconfirm -S cmake
sudo pacman --noconfirm -S cmatrix
sudo pacman --noconfirm -S cryptsetup
sudo pacman --noconfirm -S cups
sudo pacman --noconfirm -S cups-browsed
sudo pacman --noconfirm -S cups-filters
sudo pacman --noconfirm -S cups-pdf
sudo pacman --noconfirm -S device-mapper
sudo pacman --noconfirm -S diffutils
sudo pacman --noconfirm -S dmidecode
sudo pacman --noconfirm -S dmraid
sudo pacman --noconfirm -S dnsmasq
sudo pacman --noconfirm -S dolphin
sudo pacman --noconfirm -S dosfstools
sudo pacman --noconfirm -S downgrade
sudo pacman --noconfirm -S dracut
sudo pacman --noconfirm -S duf
sudo pacman --noconfirm -S dunst
sudo pacman --noconfirm -S e2fsprogs
sudo pacman --noconfirm -S efibootmgr
sudo pacman --noconfirm -S efitools
sudo pacman --noconfirm -S endeavouros-branding
sudo pacman --noconfirm -S endeavouros-keyring
sudo pacman --noconfirm -S endeavouros-mirrorlist
sudo pacman --noconfirm -S eos-apps-info
sudo pacman --noconfirm -S eos-hooks
sudo pacman --noconfirm -S eos-log-tool
sudo pacman --noconfirm -S eos-packagelist
sudo pacman --noconfirm -S eos-quickstart
sudo pacman --noconfirm -S eos-rankmirrors
sudo pacman --noconfirm -S ethtool
sudo pacman --noconfirm -S exfatprogs
sudo pacman --noconfirm -S f2fs-tools
sudo pacman --noconfirm -S ffmpegthumbnailer
sudo pacman --noconfirm -S firewalld
sudo pacman --noconfirm -S flameshot
sudo pacman --noconfirm -S fontforge
sudo pacman --noconfirm -S foomatic-db
sudo pacman --noconfirm -S foomatic-db-engine
sudo pacman --noconfirm -S foomatic-db-gutenprint-ppds
sudo pacman --noconfirm -S foomatic-db-nonfree
sudo pacman --noconfirm -S foomatic-db-nonfree-ppds
sudo pacman --noconfirm -S foomatic-db-ppds
sudo pacman --noconfirm -S gdb
sudo pacman --noconfirm -S ghostscript
sudo pacman --noconfirm -S git
sudo pacman --noconfirm -S glances
sudo pacman --noconfirm -S godot
sudo pacman --noconfirm -S gsfonts
sudo pacman --noconfirm -S gst-libav
sudo pacman --noconfirm -S gst-plugin-pipewire
sudo pacman --noconfirm -S gst-plugins-bad
sudo pacman --noconfirm -S gst-plugins-ugly
sudo pacman --noconfirm -S gutenprint
sudo pacman --noconfirm -S haveged
sudo pacman --noconfirm -S hdf5
sudo pacman --noconfirm -S hdparm
sudo pacman --noconfirm -S heroic-games-launcher-bin
sudo pacman --noconfirm -S hwdetect
sudo pacman --noconfirm -S hwinfo
sudo pacman --noconfirm -S hyprland
sudo pacman --noconfirm -S hyprpaper
sudo pacman --noconfirm -S hyprshot
sudo pacman --noconfirm -S inetutils
sudo pacman --noconfirm -S inkscape
sudo pacman --noconfirm -S inxi
sudo pacman --noconfirm -S iptables-nft
sudo pacman --noconfirm -S iwd
sudo pacman --noconfirm -S jfsutils
sudo pacman --noconfirm -S kernel-install-for-dracut
sudo pacman --noconfirm -S less
sudo pacman --noconfirm -S lib32-mesa
sudo pacman --noconfirm -S lib32-vulkan-intel
sudo pacman --noconfirm -S libdvdcss
sudo pacman --noconfirm -S libgsf
sudo pacman --noconfirm -S libopenraw
sudo pacman --noconfirm -S libreoffice-still
sudo pacman --noconfirm -S libwnck3
sudo pacman --noconfirm -S linux
sudo pacman --noconfirm -S linux-firmware
sudo pacman --noconfirm -S linux-headers
sudo pacman --noconfirm -S linux-lts
sudo pacman --noconfirm -S linux-lts-headers
sudo pacman --noconfirm -S logrotate
sudo pacman --noconfirm -S love
sudo pacman --noconfirm -S lsb-release
sudo pacman --noconfirm -S lsscsi
sudo pacman --noconfirm -S lvm2
sudo pacman --noconfirm -S man-db
sudo pacman --noconfirm -S man-pages
sudo pacman --noconfirm -S mdadm
sudo pacman --noconfirm -S meld
sudo pacman --noconfirm -S mesa-utils
sudo pacman --noconfirm -S modemmanager
sudo pacman --noconfirm -S mpv
sudo pacman --noconfirm -S mtools
sudo pacman --noconfirm -S nano
sudo pacman --noconfirm -S nano-syntax-highlighting
sudo pacman --noconfirm -S neofetch
sudo pacman --noconfirm -S neovim
sudo pacman --noconfirm -S netctl
sudo pacman --noconfirm -S networkmanager
sudo pacman --noconfirm -S networkmanager-openconnect
sudo pacman --noconfirm -S networkmanager-openvpn
sudo pacman --noconfirm -S nfs-utils
sudo pacman --noconfirm -S nilfs-utils
sudo pacman --noconfirm -S noto-fonts
sudo pacman --noconfirm -S noto-fonts-cjk
sudo pacman --noconfirm -S noto-fonts-emoji
sudo pacman --noconfirm -S noto-fonts-extra
sudo pacman --noconfirm -S nss-mdns
sudo pacman --noconfirm -S ntfs-3g
sudo pacman --noconfirm -S ntp
sudo pacman --noconfirm -S obs-studio
sudo pacman --noconfirm -S opencv
sudo pacman --noconfirm -S openssh
sudo pacman --noconfirm -S pacman-contrib
sudo pacman --noconfirm -S parted
sudo pacman --noconfirm -S pavucontrol
sudo pacman --noconfirm -S perl
sudo pacman --noconfirm -S pipes.sh
sudo pacman --noconfirm -S pipewire-alsa
sudo pacman --noconfirm -S pipewire-jack
sudo pacman --noconfirm -S pipewire-pulse
sudo pacman --noconfirm -S pkgfile
sudo pacman --noconfirm -S plocate
sudo pacman --noconfirm -S poppler-glib
sudo pacman --noconfirm -S power-profiles-daemon
sudo pacman --noconfirm -S pv
sudo pacman --noconfirm -S python
sudo pacman --noconfirm -S python-defusedxml
sudo pacman --noconfirm -S python-packaging
sudo pacman --noconfirm -S python-pip
sudo pacman --noconfirm -S python-pipx
sudo pacman --noconfirm -S python-pyqt6
sudo pacman --noconfirm -S qt5-wayland
sudo pacman --noconfirm -S raylib
sudo pacman --noconfirm -S rebuild-detector
sudo pacman --noconfirm -S reflector
sudo pacman --noconfirm -S reflector-simple
sudo pacman --noconfirm -S rofi
sudo pacman --noconfirm -S rsync
sudo pacman --noconfirm -S rtkit
sudo pacman --noconfirm -S s-nail
sudo pacman --noconfirm -S sg3_utils
sudo pacman --noconfirm -S smartmontools
sudo pacman --noconfirm -S sof-firmware
sudo pacman --noconfirm -S splix
sudo pacman --noconfirm -S steam
sudo pacman --noconfirm -S sudo
sudo pacman --noconfirm -S sysfsutils
sudo pacman --noconfirm -S system-config-printer
sudo pacman --noconfirm -S systemd-sysvcompat
sudo pacman --noconfirm -S texinfo
sudo pacman --noconfirm -S thorium-browser-avx2-bin
sudo pacman --noconfirm -S thunderbird-bin
sudo pacman --noconfirm -S tldr
sudo pacman --noconfirm -S tree
sudo pacman --noconfirm -S ttf-bitstream-vera
sudo pacman --noconfirm -S ttf-dejavu
sudo pacman --noconfirm -S ttf-hack-nerd
sudo pacman --noconfirm -S ttf-liberation
sudo pacman --noconfirm -S ttf-opensans
sudo pacman --noconfirm -S udevil-git
sudo pacman --noconfirm -S udiskie
sudo pacman --noconfirm -S unrar
sudo pacman --noconfirm -S unzip
sudo pacman --noconfirm -S upower
sudo pacman --noconfirm -S usb_modeswitch
sudo pacman --noconfirm -S usbutils
sudo pacman --noconfirm -S vi
sudo pacman --noconfirm -S vulkan-intel
sudo pacman --noconfirm -S vulkan-tools
sudo pacman --noconfirm -S waybar
sudo pacman --noconfirm -S welcome
sudo pacman --noconfirm -S wget
sudo pacman --noconfirm -S which
sudo pacman --noconfirm -S wireplumber
sudo pacman --noconfirm -S wpa_supplicant
sudo pacman --noconfirm -S xclip
sudo pacman --noconfirm -S xdg-user-dirs
sudo pacman --noconfirm -S xdg-utils
sudo pacman --noconfirm -S xf86-input-libinput
sudo pacman --noconfirm -S xfsprogs
sudo pacman --noconfirm -S xl2tpd
sudo pacman --noconfirm -S xorg-server
sudo pacman --noconfirm -S xorg-xdpyinfo
sudo pacman --noconfirm -S xorg-xev
sudo pacman --noconfirm -S xorg-xinit
sudo pacman --noconfirm -S xorg-xinput
sudo pacman --noconfirm -S xorg-xkill
sudo pacman --noconfirm -S xorg-xrandr
sudo pacman --noconfirm -S xterm
sudo pacman --noconfirm -S yay
sudo pacman --noconfirm -S zoxide
