sudo pacman -S accountsservice
sudo pacman -S alacritty
sudo pacman -S alsa-firmware
sudo pacman -S alsa-plugins
sudo pacman -S alsa-utils
sudo pacman -S amd-ucode
sudo pacman -S aspell
sudo pacman -S astroterm
sudo pacman -S b43-fwcutter
sudo pacman -S base
sudo pacman -S base-devel
sudo pacman -S bash-completion
sudo pacman -S bc
sudo pacman -S bind
sudo pacman -S bluez
sudo pacman -S bluez-utils
sudo pacman -S btrfs-progs
sudo pacman -S cantarell-fonts
sudo pacman -S cava
sudo pacman -S chafa
sudo pacman -S clipman
sudo pacman -S cloc
sudo pacman -S cmake
sudo pacman -S cmatrix
sudo pacman -S cryptsetup
sudo pacman -S cups
sudo pacman -S cups-browsed
sudo pacman -S cups-filters
sudo pacman -S cups-pdf
sudo pacman -S device-mapper
sudo pacman -S diffutils
sudo pacman -S dmidecode
sudo pacman -S dmraid
sudo pacman -S dnsmasq
sudo pacman -S dolphin
sudo pacman -S dosfstools
sudo pacman -S downgrade
sudo pacman -S dracut
sudo pacman -S duf
sudo pacman -S dunst
sudo pacman -S e2fsprogs
sudo pacman -S efibootmgr
sudo pacman -S efitools
sudo pacman -S endeavouros-branding
sudo pacman -S endeavouros-keyring
sudo pacman -S endeavouros-mirrorlist
sudo pacman -S eos-apps-info
sudo pacman -S eos-hooks
sudo pacman -S eos-log-tool
sudo pacman -S eos-packagelist
sudo pacman -S eos-quickstart
sudo pacman -S eos-rankmirrors
sudo pacman -S ethtool
sudo pacman -S exfatprogs
sudo pacman -S f2fs-tools
sudo pacman -S ffmpegthumbnailer
sudo pacman -S firewalld
sudo pacman -S flameshot
sudo pacman -S fontforge
sudo pacman -S foomatic-db
sudo pacman -S foomatic-db-engine
sudo pacman -S foomatic-db-gutenprint-ppds
sudo pacman -S foomatic-db-nonfree
sudo pacman -S foomatic-db-nonfree-ppds
sudo pacman -S foomatic-db-ppds
sudo pacman -S gdb
sudo pacman -S ghostscript
sudo pacman -S git
sudo pacman -S glances
sudo pacman -S godot
sudo pacman -S gsfonts
sudo pacman -S gst-libav
sudo pacman -S gst-plugin-pipewire
sudo pacman -S gst-plugins-bad
sudo pacman -S gst-plugins-ugly
sudo pacman -S gutenprint
sudo pacman -S haveged
sudo pacman -S hdf5
sudo pacman -S hdparm
sudo pacman -S heroic-games-launcher-bin
sudo pacman -S hwdetect
sudo pacman -S hwinfo
sudo pacman -S hyprland
sudo pacman -S hyprpaper
sudo pacman -S hyprshot
sudo pacman -S inetutils
sudo pacman -S inkscape
sudo pacman -S inxi
sudo pacman -S iptables-nft
sudo pacman -S iwd
sudo pacman -S jfsutils
sudo pacman -S kernel-install-for-dracut
sudo pacman -S less
sudo pacman -S lib32-mesa
sudo pacman -S lib32-vulkan-intel
sudo pacman -S libdvdcss
sudo pacman -S libgsf
sudo pacman -S libopenraw
sudo pacman -S libreoffice-still
sudo pacman -S libwnck3
sudo pacman -S linux
sudo pacman -S linux-firmware
sudo pacman -S linux-headers
sudo pacman -S linux-lts
sudo pacman -S linux-lts-headers
sudo pacman -S logrotate
sudo pacman -S love
sudo pacman -S lsb-release
sudo pacman -S lsscsi
sudo pacman -S lvm2
sudo pacman -S man-db
sudo pacman -S man-pages
sudo pacman -S mdadm
sudo pacman -S meld
sudo pacman -S mesa-utils
sudo pacman -S modemmanager
sudo pacman -S mpv
sudo pacman -S mtools
sudo pacman -S nano
sudo pacman -S nano-syntax-highlighting
sudo pacman -S neofetch
sudo pacman -S neovim
sudo pacman -S netctl
sudo pacman -S networkmanager
sudo pacman -S networkmanager-openconnect
sudo pacman -S networkmanager-openvpn
sudo pacman -S nfs-utils
sudo pacman -S nilfs-utils
sudo pacman -S noto-fonts
sudo pacman -S noto-fonts-cjk
sudo pacman -S noto-fonts-emoji
sudo pacman -S noto-fonts-extra
sudo pacman -S nss-mdns
sudo pacman -S ntfs-3g
sudo pacman -S ntp
sudo pacman -S obs-studio
sudo pacman -S opencv
sudo pacman -S openssh
sudo pacman -S pacman-contrib
sudo pacman -S parted
sudo pacman -S pavucontrol
sudo pacman -S perl
sudo pacman -S pipes.sh
sudo pacman -S pipewire-alsa
sudo pacman -S pipewire-jack
sudo pacman -S pipewire-pulse
sudo pacman -S pkgfile
sudo pacman -S plocate
sudo pacman -S poppler-glib
sudo pacman -S power-profiles-daemon
sudo pacman -S pv
sudo pacman -S python
sudo pacman -S python-defusedxml
sudo pacman -S python-packaging
sudo pacman -S python-pip
sudo pacman -S python-pipx
sudo pacman -S python-pyqt6
sudo pacman -S qt5-wayland
sudo pacman -S raylib
sudo pacman -S rebuild-detector
sudo pacman -S reflector
sudo pacman -S reflector-simple
sudo pacman -S rofi
sudo pacman -S rsync
sudo pacman -S rtkit
sudo pacman -S s-nail
sudo pacman -S sg3_utils
sudo pacman -S smartmontools
sudo pacman -S sof-firmware
sudo pacman -S splix
sudo pacman -S steam
sudo pacman -S sudo
sudo pacman -S sysfsutils
sudo pacman -S system-config-printer
sudo pacman -S systemd-sysvcompat
sudo pacman -S texinfo
sudo pacman -S thorium-browser-avx2-bin
sudo pacman -S thunderbird-bin
sudo pacman -S tldr
sudo pacman -S tree
sudo pacman -S ttf-bitstream-vera
sudo pacman -S ttf-dejavu
sudo pacman -S ttf-hack-nerd
sudo pacman -S ttf-liberation
sudo pacman -S ttf-opensans
sudo pacman -S udevil-git
sudo pacman -S udiskie
sudo pacman -S unrar
sudo pacman -S unzip
sudo pacman -S upower
sudo pacman -S usb_modeswitch
sudo pacman -S usbutils
sudo pacman -S vi
sudo pacman -S vulkan-intel
sudo pacman -S vulkan-tools
sudo pacman -S waybar
sudo pacman -S welcome
sudo pacman -S wget
sudo pacman -S which
sudo pacman -S wireplumber
sudo pacman -S wpa_supplicant
sudo pacman -S xclip
sudo pacman -S xdg-user-dirs
sudo pacman -S xdg-utils
sudo pacman -S xf86-input-libinput
sudo pacman -S xfsprogs
sudo pacman -S xl2tpd
sudo pacman -S xorg-server
sudo pacman -S xorg-xdpyinfo
sudo pacman -S xorg-xev
sudo pacman -S xorg-xinit
sudo pacman -S xorg-xinput
sudo pacman -S xorg-xkill
sudo pacman -S xorg-xrandr
sudo pacman -S xterm
sudo pacman -S yay
sudo pacman -S zoxide
